apiVersion: 1
deleteDatasources: []
datasources:
  - basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 30s
    name: Prometheus
    type: prometheus
    url: http://prometheus:9090
