// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PushGatewayClient is the client API for PushGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushGatewayClient interface {
	OrderBook(ctx context.Context, in *GatewayRequest, opts ...grpc.CallOption) (*GatewayResponse, error)
}

type pushGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewPushGatewayClient(cc grpc.ClientConnInterface) PushGatewayClient {
	return &pushGatewayClient{cc}
}

func (c *pushGatewayClient) OrderBook(ctx context.Context, in *GatewayRequest, opts ...grpc.CallOption) (*GatewayResponse, error) {
	out := new(GatewayResponse)
	err := c.cc.Invoke(ctx, "/PushGateway/OrderBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushGatewayServer is the server API for PushGateway service.
// All implementations must embed UnimplementedPushGatewayServer
// for forward compatibility
type PushGatewayServer interface {
	OrderBook(context.Context, *GatewayRequest) (*GatewayResponse, error)
	mustEmbedUnimplementedPushGatewayServer()
}

// UnimplementedPushGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedPushGatewayServer struct {
}

func (UnimplementedPushGatewayServer) OrderBook(context.Context, *GatewayRequest) (*GatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderBook not implemented")
}
func (UnimplementedPushGatewayServer) mustEmbedUnimplementedPushGatewayServer() {}

// UnsafePushGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushGatewayServer will
// result in compilation errors.
type UnsafePushGatewayServer interface {
	mustEmbedUnimplementedPushGatewayServer()
}

func RegisterPushGatewayServer(s grpc.ServiceRegistrar, srv PushGatewayServer) {
	s.RegisterService(&PushGateway_ServiceDesc, srv)
}

func _PushGateway_OrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushGatewayServer).OrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PushGateway/OrderBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushGatewayServer).OrderBook(ctx, req.(*GatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PushGateway_ServiceDesc is the grpc.ServiceDesc for PushGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PushGateway",
	HandlerType: (*PushGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderBook",
			Handler:    _PushGateway_OrderBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
