{
 "title": "Go Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(go_goroutines, job)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(go_goroutines, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=\"$Instance\", job=~\"$Job\"}  "
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=\"$Instance\", job=~\"$Job\"} - go_memstats_other_sys_bytes{instance=\"$Instance\", job=~\"$Job\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"$Instance\", job=~\"$Job\"} "
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"$Instance\", job=~\"$Job\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=\"$Instance\", job=~\"$Job\"} - go_memstats_frees_total{instance=\"$Instance\", job=~\"$Job\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=\"$Instance\", job=~\"$Job\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{instance=\"$Instance\", job=~\"$Job\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$Instance\", job=~\"$Job\"}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"$Instance\", job=~\"$Job\"}[1m])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"$Instance\", job=~\"$Job\"}"
    }
   ]
  }
 ]
}